### ISSUE TITLE
"Search" does not enter history correctly

### ISSUE THREAD

**Issue by tkoeppe** [chrishayesmu/XCOM-Companion#4] opened 2021-05-31 23:48 UTC
To reproduce:

1. Ctrl-F to search for some page; visit that page.
2. Press the "Back" button. (Correctly returns you to the previously displayed page.)
3. Press the "Next page button". (Fails, does not return to the searched-for page from step 1.)

**Comment by chrishayesmu** [comment] 2021-05-31 23:56
I couldn't reproduce this. Which page were you searching for? It might be that page which is failing to enter history correctly.

**Comment by tkoeppe** [comment] 2021-06-01 08:47
Ah, it does indeed seem to depend on the page! Try with "Abductor - Cliffside".

**Comment by chrishayesmu** [comment] 2021-06-01 17:09
Oh yep, looks like I forgot to handle history when I added that page. Fixed in https://github.com/chrishayesmu/XCOM-Companion/commit/72e5d050965fc3b61c57b0c5144b19d0a9c702d6. Thanks for the report!

**Closed as completed by chrishayesmu** 2021-06-01 17:09 UTC

**Comment by tkoeppe** [comment] 2021-06-01 17:16
Grand, thanks!
